INSERT INTO TB_ALUNO(NOM_ALUNO,DES_EMAIL) 
VALUES ('Tiririca','florentina@gmail.com');

INSERT INTO TB_ALUNO(NOM_ALUNO,DES_EMAIL) 
VALUES ('Sergio Malandro','ieie@gmail.com');

INSERT INTO TB_DISCIPLINA(NOM_DISCIPLINA,DES_EMENTA,NUM_HORAS)
VALUES ('PROJETO ORM COM JPA','HIBERNATE, POO',84);

INSERT INTO TB_DISCIPLINA(NOM_DISCIPLINA,DES_EMENTA,NUM_HORAS)
VALUES ('GESTAO DE PROJETOS','GARGALHADA',42);

 INSERT INTO TB_ALUNOS_CURSANDO(COD_ALUNO,COD_DISCIPLINA) VALUES(1,1);
 INSERT INTO TB_ALUNOS_CURSANDO(COD_ALUNO,COD_DISCIPLINA) VALUES(1,2);
 INSERT INTO TB_ALUNOS_CURSANDO(COD_ALUNO,COD_DISCIPLINA) VALUES(2,2);
